### PR TITLE
Fix debugger hanging with slow loading source maps

### LINKED ISSUE #7301: Debugger panel hangs for minutes if loading one or more source maps times out
Steps to reproduce:

1) Go on airbnb.com
2) Open the debugger

screen shot 2018-11-19 at 13 40 38

The problem is that loading source maps for most of Airbnb's bundles timeouts, as the files seem to be served only inside their network.

If you wait long enough for all the source maps to timeout (many minutes), eventually the debugger UI shows up and is functional.

### PR DESCRIPTION
**Pull request by alessandrod**
Fixes #7301 

The fix involves:
- making newSources() not wait for source maps to be loaded
- making loadSourceMaps() add each map to the state asap, instead of doing one big add once all the source maps are loaded

I added two tests that model the current bug and that fail if the two changes above are reverted.

### CODE REVIEW

**Comment by jasonLaster** [comment]
This is a difficult issue to get right because if we update the Redux store, too often we cause performance issues for apps like (angular todos) which have one source map per file. 

https://w2x2oypmqk.codesandbox.io/

I'd love your help fine tuning this because what we have now clearly doesn't work either...

File: src/actions/sources/newSources.js [hunk 1]
```diff
@@ -184,7 +185,7 @@ export function newSources(sources: Source[]) {
 
     dispatch(({ type: "ADD_SOURCES", sources: sources }: Action));
 
-    await dispatch(loadSourceMaps(sources));
```
Comment (jasonLaster) [inline src/actions/sources/newSources.js]: I think this is safe to do

File: src/actions/sources/newSources.js [hunk 2]
```diff
@@ -50,14 +49,16 @@ function loadSourceMaps(sources) {
...
-      sources.map(({ id }) => dispatch(loadSourceMap(id)))
+    await Promise.all(
+      sources.map(({ id }) =>
+        dispatch(loadSourceMap(id)).then(originalSource => {
+          if (originalSource) {
+            dispatch(newSources(originalSource));
+          }
+          return originalSource;
+        })
+      )
```
Comment (jasonLaster) [inline src/actions/sources/newSources.js]: I don't think we need to return anything, so if do this it could be much simpler

```js
sources.map(async ({ id }) => {
  const originalSources = await dispatch(loadSourceMap(id));
   if (originalSources) {
      dispatch(newSources(originalSource));
    }
 })
```

My concern with this approach is that in the case of an angular app this could be 500+ redux calls to newSources..  Of course, we can add some throttling in `newSources` so at most we dispatch the new sources every 50ms.

Comment (jasonLaster) [reply src/actions/sources/newSources.js]: I was trying to think what a throttled addSources would look like and I think this is a reasonable approximation

```diff
diff --git a/src/actions/sources/newSources.js b/src/actions/sources/newSources.js
index 2c5b52d98..5466039e0 100644
--- a/src/actions/sources/newSources.js
+++ b/src/actions/sources/newSources.js
@@ -174,6 +174,14 @@ export function newSource(source: Source) {
   };
 }

+let throttledSources = []
+const addSources = debounce(() => {
+  return ({ dispatch, getState }: ThunkArgs) => {
+    dispatch(({ type: "ADD_SOURCES", sources: throttledSources }: Action));
+    throttledSources = [];
+  }
+}
+
 export function newSources(sources: Source[]) {
   return async ({ dispatch, getState }: ThunkArgs) => {
     sources = sources.filter(source => !getSource(getState(), source.id));
@@ -182,7 +190,8 @@ export function newSources(sources: Source[]) {
       return;
     }

-    dispatch(({ type: "ADD_SOURCES", sources: sources }: Action));
+    throttledSources = [...throttledSources, ...sources]
+    dispatch(addSources())

     await dispatch(loadSourceMaps(sources));
```

Comment (jasonLaster) [reply src/actions/sources/newSources.js]: Maybe an even smarter way to do this would be to re-use the same throttled source queue we use in [firefox/events.js](https://github.com/devtools-html/debugger.html/blob/master/src/client/firefox/events.js#L102-L103)

https://github.com/devtools-html/debugger.html/blob/master/src/utils/source-queue.js#L20


```diff
diff --git a/src/actions/sources/newSources.js b/src/actions/sources/newSources.js
index 2c5b52d98..3dd0d1e3f 100644
--- a/src/actions/sources/newSources.js
+++ b/src/actions/sources/newSources.js
@@ -25,6 +25,7 @@ import {
   getPendingBreakpointsForSource
 } from "../../selectors";
 
+import sourceQueue from "../../utils/source-queue";
 import type { Source, SourceId } from "../../types";
 import type { Action, ThunkArgs } from "../types";
 
@@ -50,14 +51,10 @@ function loadSourceMaps(sources) {
       return;
     }
 
-    let originalSources = await Promise.all(
-      sources.map(({ id }) => dispatch(loadSourceMap(id)))
-    );
-
-    originalSources = flatten(originalSources).filter(Boolean);
-    if (originalSources.length > 0) {
-      await dispatch(newSources(originalSources));
-    }
+    sources.map(async ({ id }) => {
+      const originalSources = await dispatch(loadSourceMap(id));
+      queueSources(originalSource);
+    });
   };
 }
 
diff --git a/src/utils/source-queue.js b/src/utils/source-queue.js
index 4c6428df8..0338edb8b 100644
--- a/src/utils/source-queue.js
+++ b/src/utils/source-queue.js
@@ -32,6 +32,11 @@ export default {
     queuedSources.push(source);
     queue();
   },
+  queueSources: sources => {
+    queuedSources = queuedSources.concat(sources);
+    queue();
+  },
+
   flush: () => Promise.all([queue.flush(), currentWork]),
   clear: () => queue.cancel()
};
```

This solution strikes me as particularly elegant as we're re-using the throttling that already exists and would be able to add new original sources pretty smoothly

Comment (alessandrod) [reply src/actions/sources/newSources.js]: Alright, I've made newSources use source-queue and updated the unit tests accordingly. Mochitests are failing on travis now, going to try to reproduce those failures locally now.

Comment (alessandrod) [reply src/actions/sources/newSources.js]: Running mochitests on my laptop takes a while so I've only managed to do 3 complete runs, the result is this:

```
Overall Summary
===============

mochitest-browser
~~~~~~~~~~~~~~~~~
Ran 2878 checks (73 tests, 2805 subtests)
Expected results: 2872
Skipped: 3 tests
Unexpected results: 2
  subtest: 2 (2 fail)

Unexpected Results
------------------
devtools/client/debugger/new/test/mochitest/browser_dbg-breakpoints-columns.js
  FAIL Test timed out -
devtools/client/debugger/new/test/mochitest/browser_dbg-tabs-keyboard.js
  FAIL Uncaught exception - at chrome://mochitests/content/browser/devtools/client/debugger/new/test/mochitest/helpers.js:605 - TypeError: findElement(...) is null; can't access its "children" property
Stack trace:
countTabs@chrome://mochitests/content/browser/devtools/client/debugger/new/test/mochitest/helpers.js:605:10
@chrome://mochitests/content/browser/devtools/client/debugger/new/test/mochitest/browser_dbg-tabs-keyboard.js:15:6
Async*Tester_execTest/<@chrome://mochikit/content/browser-test.js:1093:34
async*Tester_execTest@chrome://mochikit/content/browser-test.js:1084:16
nextTest/<@chrome://mochikit/content/browser-test.js:982:9
SimpleTest.waitForFocus/waitForFocusInner/focusedOrLoaded/<@chrome://mochikit/content/tests/SimpleTest/SimpleTest.js:803:59
```

Those two tests fail reproducibly. I'm not seeing all those time outs that seem to happen on travis.

**Comment by AnshulMalik** [comment]
This is awesome. I have a patch to fix the tests :)

File: src/actions/sources/newSources.js [hunk 3]
```diff
@@ -52,14 +52,12 @@ function loadSourceMaps(sources) {
...
-    let originalSources = await Promise.all(
-      sources.map(({ id }) => dispatch(loadSourceMap(id)))
-    );
-
-    originalSources = flatten(originalSources).filter(Boolean);
-    if (originalSources.length > 0) {
-      await dispatch(newSources(originalSources));
-    }
+    sources.map(async ({ id }) => {
+      const originalSources = await dispatch(loadSourceMap(id));
```
Comment (jasonLaster) [inline src/actions/sources/newSources.js]: can we have always return an array? and enforce it with flow?

File: src/utils/source-queue.js [hunk 4]
```diff
@@ -32,6 +32,16 @@ export default {
     queuedSources.push(source);
     queue();
   },
+  queueSources: sources => {
+    queuedSources = queuedSources.concat(
+      sources.map(source => {
+        source.actor = source.id;
```
Comment (alessandrod) [inline src/utils/source-queue.js]: Thanks for fixing the tests!

Why is this required here tho? Shouldn't the callers set source.actor if it's required?

Comment (AnshulMalik) [reply src/utils/source-queue.js]: There are few possibilities where we can add actor as property, or use `id` everywhere(it's what we should do in future for CDP compatibility). I just wanted to see if this fixes things.

We can either say `source.actor || source.id` [here](https://github.com/devtools-html/debugger.html/blob/master/src/client/firefox/create.js#L48)
and fix flow, this would be what I'd do but flow is upset with me.

File: src/actions/sources/newSources.js (hunk 3 above)
Comment (alessandrod) [reply src/actions/sources/newSources.js]: Right, done.

File: src/utils/source-queue.js (hunk 4 above)
Comment (alessandrod) [reply src/utils/source-queue.js]: The type `Source` defines an [id property](https://github.com/devtools-html/debugger.html/blob/fcff67bcf43a118ba7c967a0445df9006b75176a/src/types.js#L294) while `SourcePayload` defines an [actor property](https://github.com/devtools-html/debugger.html/blob/5bc3da76eab9ac5d160c88e1dc5aaeb63b56f20a/src/client/firefox/types.js#L86). Is SourcePayload supposed to be a serialized Source? If so SourcePayload.actor should probably become SourcePayload.id?

Comment (AnshulMalik) [reply src/utils/source-queue.js]: So, SourcePayload is for what we get from the server, that is, source id as `actor` property.
But on the client side, we don't use the actor property instead we use `id`.
Ideally, we'd want the server to send us `id` and not `actor`
But for now, we'd have to make a patch somewhere.

File: src/actions/sources/newSources.js [hunk 5]
```diff
@@ -46,20 +47,24 @@ function createOriginalSource(
...
-      return;
+      return [];
     }
 
-    let originalSources = await Promise.all(
-      sources.map(({ id }) => dispatch(loadSourceMap(id)))
+    return flatten(
+      sources.map(async ({ id }) => {
+        const originalSources = await dispatch(loadSourceMap(id));
+        if (originalSources !== undefined) {
```
Comment (AnshulMalik) [inline src/actions/sources/newSources.js]: I think now we don't need this check, since we know it'd never be `undefined`

Comment (jasonLaster) [reply src/actions/sources/newSources.js]: nope, no objection.

Comment (alessandrod) [reply src/actions/sources/newSources.js]: Alright, I've annotated `loadSourceMap` to return `Promise<Source[]>` and fixed the return points. I've updated `test-head.js` so that all tests initialize the `sourceQueue` as per my previous comment.

Then I've actually reinstated the following check tho:
```diff
+        const originalSources = await dispatch(loadSourceMap(id));
+        if (originalSources.length > 0) {
+          sourceQueue.queueSources(originalSources);
+        }
```

Otherwise whenever called - even with an empty array - `queueSources` internally will create a new array and schedule a new dispatchNewSources call, which seems not ideal. I opted for checking that the array is not empty before calling `queueSources` since it's closer to where the array is created, and it's obvious why it'd be valid for it to be empty. You could argue that `queueSources` should return early if `sources.length == 0` tho and I'm happy to do that if anyone thinks it's better.

File: src/utils/source-queue.js (hunk 4 above)
Comment (AnshulMalik) [reply src/utils/source-queue.js]: So we call this `createSource` [function](https://github.com/devtools-html/debugger.html/blob/master/src/client/firefox/create.js#L43) when we get a new source from the server, which has the actor property.

But we also use this function to create a source from original urls(which are generated on client side) and has `id` instead of `actor`. So those original sources gets generated without an id, which causes further issues.

I have not looked into it in much detail as to find a nice solution. But I am confident that you'll find some nice answer.

Comment (alessandrod) [reply src/utils/source-queue.js]: Thanks that really helped me understand the problem!

The problem is that now the same `sourceQueue` is used to create sources coming from the firefox server (received as instances of type `SourcePayload`), and from the client (instances of type `Source`). That's problematic since the types don't have matching fields, and the client is supposed to abstract over server implementations anyway. 

One possible solution is to refactor `source-queue.js` so that it's not a module-singleton and use two separate queues, one for sources coming from the server and another for sources coming from the client. There's other simpler solutions similar to your fix, but applied to `src/client/firefox`. @jasonLaster opinions?

Comment (jasonLaster) [reply src/utils/source-queue.js]: Good question. 

I think I would change the newSource function so it calls createSource before enquing the source. 

This should be simpler too

File: src/actions/sources/newSources.js [hunk 6]
```diff
@@ -46,20 +47,24 @@ function createOriginalSource(
...
+    sourceMaps
+  }: ThunkArgs): Promise<Promise<Source>[]> {
     if (!prefs.clientSourceMapsEnabled) {
-      return;
+      return [];
     }
 
-    let originalSources = await Promise.all(
-      sources.map(({ id }) => dispatch(loadSourceMap(id)))
+    return flatten(
```
Comment (jasonLaster) [inline src/actions/sources/newSources.js]: we don't really use the return value of this function, but it is nice to keep it as an array of original sources for debugging purposes.

**Comment by jasonLaster** [comment]
just rebased, hopefully it will be green now

**Comment by jasonLaster** [comment]
The tests should now be green. Lets just test one more time to make things are good

**Comment by alessandrod** [comment]
This is great! Thanks so much for your help Jason and Anshul! :)
