### PR TITLE
[Breakpoints] fix breakpoint context menu logic

### LINKED ISSUE #7268: [breakpoints] disable others no longer works
STR:

1. add a bunch of breakpoints
2. in the breakpoint panel right click a breakpoint and select disable others

This fixes it
https://gist.github.com/4f26899b282ebc2e735aebc060d41525

But, we should also add a jest or mochitest test

### PR DESCRIPTION
**Pull request by kenjiO**
Fixes #7268 

### Summary of Changes

* update BreakpointContextMenu.js logic that finds other breakpoints.  A formatted breakpoint object was being compared to a breakpoint object using object equality which was always returning that they were not the same breakpoint.  I changed it to compare using breakpoint id.
* added the breakpoint id property to FormattedBreakpoint objects

### CODE REVIEW

File: src/test/mochitest/browser_dbg-breakpoints-actions.js [hunk 1]
```diff
@@ -14,8 +13,58 @@ add_task(async function() {
...
+    dbg.selectors.getBreakpointsList(state).every(bp => bp.disabled)
+  );
+  ok("all breakpoints are disabled")
+
+  openFirstBreakpointContextMenu(dbg)
+  // select "Enable Others"
+  selectMenuItem(dbg, 3);
+  await waitForState(dbg, state =>
+    dbg.selectors.getBreakpointsList(state)
+      .every(bp => (bp.location.line === 1) === bp.disabled)
```
Comment (jasonLaster) [inline src/test/mochitest/browser_dbg-breakpoints-actions.js]: okay, this is the craziest thing I've seen in awhile, but it's a test so lets go crazy

**Comment by jasonLaster** [comment]
This is beautiful. I love that you opened two PRs by the way, that really helps keep things moving
