### PR TITLE
[Fix for #7851] After #7796 relativeSources attributes were not updated

### LINKED ISSUE #7851: [SourcesTree] state.sources.relativeSources attributes not updated with new data
Steps to reproduce:

1. Open a source file in the editor pane
2. Debug on render

Expected:
The `loaded` attribute for the opened source within relativeSources should show `"loaded"`

Actual:
The `loaded` attribute for the opened source within relativeSources shows `"unloaded"`

Picture:
e4f1715c5f1fb0ae62c12783a333322b

In this image, the source file is already loaded is blackboxed. At the bare minimum, the `isBlackBoxed` and `loadedState` attributes are incorrect.

### PR DESCRIPTION
**Pull request by derek-li**
Fixes #7851 

This issue was caused by splitting source into source/sourceActor PR#7796.

I've added another function to update relative sources as sources are being updated. 

Demo:

relativeSources and sources have same values for attributes like isBlackBoxed, isPrettyPrinted, loadedState:
issue7851 1

sourcesTreeItem now has blackbox icon when the source is blackboxed:
issue7851 2

### CODE REVIEW

File: src/reducers/sources.js [hunk 1]
```diff
@@ -276,10 +276,24 @@ function updateSource(state: SourcesState, source: Object) {
...
+  for (const thread in relativeSources) {
+    relativeSources[thread] = { ...relativeSources[thread] };
+    if (relativeSources[thread][source.id]) {
+      const existingRelativeSource = relativeSources[thread][source.id];
+      const updatedRelativeSource = { ...existingRelativeSource, ...source };
+      state.relativeSources[thread][source.id] = updatedRelativeSource;
+    }
+  }
+}
+
```
Comment (jasonLaster) [inline src/reducers/sources.js]: this change looks good. can we write some unit tests to demonstrate the bug and fix.

Comment (derek-li) [reply src/reducers/sources.js]: Hey @jasonLaster, sorry for the late response. Was doing some reading on jest tests and forgot to comment. 

Do you still need help with the unit tests?

Comment (darkwing) [reply src/reducers/sources.js]: I'd love if you could put a few unit tests together!

This is really impressive work @derek-li !

**Comment by jasonLaster** [comment]
@derek-li no worries - i've got one that looks fine.
