### PR TITLE
Toggle "Disable Breakpoints" tooltip to "Enable Breakpoints". Fixes #…

### LINKED ISSUE #1531: Toggle "Disable Breakpoints" tooltip to "Enable Breakpoints"
Nitpicking:  If all breakpoints are disabled, then the user can enable all again with the Breakpoints toggle. I think not only the tooltip icon should toggle but also it's tooltip depending on whether you enable or disable it.

2016-12-22 14_30_28-firefox debugger - firefox developer edition

Otherwise it says "Disable" albeit the breakpoints are already disabled.

Expected results:
If I have disabled all breakpoints, and I then can enable them again: The tooltip should show "Enable breakpoints" instead of "Disable breakpoints".

### PR DESCRIPTION
**Pull request by Dalimil**
Fixes #1531

It toggles the tooltip text whenever all breakpoints become disabled, either by clicking the button or clicking each breakpoint checkbox individually.
out

### CODE REVIEW

File: src/components/CommandBar.js [hunk 1]
```diff
@@ -213,7 +213,7 @@ const CommandBar = React.createClass({
       () => toggleAllBreakpoints(!breakpointsDisabled),
       "toggleBreakpoints",
       breakpointsDisabled ? "breakpoints-disabled" : "",
-      "Disable Breakpoints"
+      breakpointsDisabled ? "Enable Breakpoints" : "Disable Breakpoints"
```
Comment (wldcordeiro) [inline src/components/CommandBar.js]: Could we move this label into L10N stuff? @jasonLaster maybe a separate PR for that.

File: src/reducers/breakpoints.js [hunk 2]
```diff
@@ -63,7 +63,9 @@ function update(state = State(), action: Action) {
           // empty strings to be truthy, i.e. an empty string is a valid
           // condition.
           condition: firstString(action.condition, bp.condition)
-        }));
+        })).set(
```
Comment (wldcordeiro) [inline src/reducers/breakpoints.js]: Weird line spacing here. I'd put `.set("breakpointsDisabled", false)` all on one line.

File: src/reducers/breakpoints.js [hunk 3]
```diff
@@ -100,14 +101,22 @@ function update(state = State(), action: Action) {
       if (action.status === "done") {
         const id = makeLocationId(action.breakpoint.location);
 
+        const bpsLeftEnabledAfter = state.breakpoints.filter(
+          x => !x.disabled
+        ).size - (state.breakpoints.get(id).disabled ? 0 : 1);
```
Comment (jasonLaster) [inline src/reducers/breakpoints.js]: this would be simpler if it was moved to after the breakpoint was updated

File: src/reducers/breakpoints.js [hunk 4]
```diff
@@ -100,14 +101,22 @@ function update(state = State(), action: Action) {
       if (action.status === "done") {
         const id = makeLocationId(action.breakpoint.location);
 
+        const bpsLeftEnabledAfter = state.breakpoints.filter(
```
Comment (jasonLaster) [inline src/reducers/breakpoints.js]: lets move this to a utility function below `allBreakpointsDisabled`

File: src/reducers/breakpoints.js [hunk 5]
```diff
@@ -100,14 +101,22 @@ function update(state = State(), action: Action) {
...
+        const updatedState = state.set(
+          "breakpointsDisabled", bpsLeftEnabledAfter <= 0
+        );
+
         if (action.disabled) {
           const bp = state.breakpoints.get(id);
-          return state.setIn(["breakpoints", id], updateObj(bp, {
+          return updatedState.setIn(["breakpoints", id], updateObj(bp, {
             loading: false, disabled: true
           }));
```
Comment (jasonLaster) [inline src/reducers/breakpoints.js]: you probably can do 

```js
const updatedState = state.setIn(["breakpoints", id], updateObj(bp, {
   loading: false, disabled: true
}))

return updatedState.set( "breakpointsDisabled", allBreakpointsDisabled())
```

File: src/strings.json [hunk 6]
```diff
@@ -1,6 +1,8 @@
 {
   "breakpoints.header": "Breakpoints",
   "breakpoints.none": "No Breakpoints",
+  "breakpoints.enable": "Enable Breakpoints",
+  "breakpoints.disable": "Disable Breakpoints",
```
Comment (jasonLaster) [inline src/strings.json]: We should also update `debugger.properties` which is used in the panel

**Comment by Dalimil** [comment]
OK, fixed.

File: src/reducers/breakpoints.js [hunk 7]
```diff
@@ -48,6 +48,10 @@ function makeLocationId(location: Location) {
   return `${location.sourceId}:${location.line}`;
 }
 
+function allBreakpointsDisabled(state) {
+  return state.breakpoints.filter(x => !x.disabled).size <= 0;
```
Comment (jasonLaster) [inline src/reducers/breakpoints.js]: i wonder if immutable has the `any`, `all`, or `some` method
