### PR TITLE
[Parser] Support object destructuring in mapOriginalExpression 

### LINKED ISSUE #7274: [Parser] mapOriginalExpression does not handle destructuring assignments well
When working on #7222 I found out that destructuring assignments are not handled properly by `mapOriginalExpression` function.

I created the following test case for `mapOriginalExpression` function and it does not pass.

```js
it("object destructuring", () => {
  const generatedExpression = mapOriginalExpression("({ a } = { a: 4 })", {
    a: "_mod.foo",
  });
  
  expect(generatedExpression).toEqual("({ a: _mod.foo } = { a: 4 })");
});
```

This is the actual output I received:

```js
({ _mod.foo: _mod.foo } = {  a: 4 });
``` 
It's obviously incorrect (it's not even a valid syntax).

Expected state:

Mapping is done correctly, i.e.
`({ a: _mod.foo } = { a: 4 })`

or `_mod.foo = ({ a: 4 }).a`

or no mapping is done at all (?).

### PR DESCRIPTION
**Pull request by P0lip**
Fixes #7274

### Summary of Changes

* Add special case covering ObjectProperty

### Test Plan

No idea, I relied on tests.

### CODE REVIEW

File: src/workers/parser/mapOriginalExpression.js [hunk 1]
```diff
@@ -10,11 +10,14 @@ import { buildScopeList } from "./getScopes";
...
 import * as t from "@babel/types";
 
-// NOTE: this will only work if we are replacing an original identifier
+// NOTE: this will only work
+// if we are replacing an original identifier or an object property
 function replaceNode(ancestors, node) {
   const ancestor = ancestors[ancestors.length - 1];
 
-  if (typeof ancestor.index === "number") {
+  if (t.isObjectProperty(ancestor.node)) {
```
Comment (loganfsmyth) [inline src/workers/parser/mapOriginalExpression.js]: I don't think this approach is the right way to go about this.

There should already be a `node.value` in the AST, AFAIK, but it looks like we are failing to find it, I assume because it has the same location as the existing `node.key`.

It _might_ actually be enough to do
```
  t.traverse(ast, (node, ancestors) => {
    if (!t.isIdentifier(node) && !t.isThisExpression(node)) {
      return;
    }

    const ancestor = ancestors[ancestors.length - 1];
    if (ancestor.node.type === "ObjectProperty" && ancestor.key !== "value") {
      return;
    }

    // ...
```

File: src/workers/parser/mapOriginalExpression.js [hunk 2]
```diff
@@ -93,6 +93,11 @@ export default function mapOriginalExpression(
       return;
     }
 
+    const ancestor = ancestors[ancestors.length - 1];
+    if (t.isObjectProperty(ancestor.node) && ancestor.key !== "value") {
```
Comment (loganfsmyth) [inline src/workers/parser/mapOriginalExpression.js]: Can you add a comment here making it clear why we do this? Something like
```
// Shorthand properties can have a key and value with `node.loc.start` value, and we only want to replace the value.
```

**Comment by darkwing** [comment]
Apologies for amount of time review is taking here @P0lip -- we're all traveling ATM.
