### PR TITLE
Fix broken source search

### LINKED ISSUE #2742: Broken project search for sources
Looks like #2524 broke the project search.

I think we can easily fix by changing [ProjectSearch](https://github.com/devtools-html/debugger.html/blob/master/src/components/ProjectSearch.js#L97-L98)

bug

### PR DESCRIPTION
**Pull request by AnshulMalik**
On selecting the source from list, the source was not
being opened in the editor

- Fixes #2742 
- In search bar, on press enter, move to next result (previously broken)

### CODE REVIEW

File: src/components/Editor/SearchBar.js [hunk 1]
```diff
@@ -470,7 +470,7 @@ class SearchBar extends Component {
   }
 
   onKeyUp(e: SyntheticKeyboardEvent) {
-    if (e.key !== "Enter" || e.key !== "F3") {
+    if (e.key !== "Enter" && e.key !== "F3") {
```
Comment (AnshulMalik) [inline src/components/Editor/SearchBar.js]: This condition was always evaluating to `true` previously.

Comment (clarkbw) [inline src/components/Editor/SearchBar.js]: 🤡

**Comment by jasonLaster** [comment]
We have an open issue for adding tests for Source Search, but I think your work with Result List and some more unit tests will help us here :)
