### PR TITLE
Fix tier 3 OS keyboard shortcuts

### LINKED ISSUE #4088: [Shortcuts] Support tier 3 OSs
CCing from [bugzilla] Landry Breuil (:gaston) 

Opening the debugger in devtools on OpenBSD triggers lots of vomit:

```
console.error:                                                                                                               
  Message: TypeError: KEYS[os] is undefined                                                                                      
  Stack:                                                                                                               
    getKeyForOS@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/client/debugger/new/debugger.js:29495:4
getKey@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/client/debugger/new/debugger.js:29491:11
```

Of course, no match for Tier3 platforms in this... :

```js
var KEYS = {
  WINNT: {
    resume: "F8",
    pause: "F8",
    stepOver: "F10",
    stepIn: "F11",
    stepOut: "Shift+F11"
  },
  Darwin: {
    resume: "Cmd+\\",
    pause: "Cmd+\\",
    stepOver: "Cmd+'",
    stepIn: "Cmd+;",
    stepOut: "Cmd+Shift+:",
    stepOutDisplay: "Cmd+Shift+;"
  },
  Linux: {
    resume: "F8",
    pause: "F8",
    stepOver: "F10",
    stepIn: "Ctrl+F11",
    stepOut: "Ctrl+Shift+F11"
  }
};
```
Please, think of the kittens and take into account the BSDs or other non-Tier1 platforms (solaris ?)

[bugzilla]:https://bugzilla.mozilla.org/show_bug.cgi?id=1400197#c1

### PR DESCRIPTION
**Pull request by jasonLaster**
fixes #4088

### CODE REVIEW

File: src/components/SecondaryPanes/CommandBar.js [hunk 1]
```diff
@@ -53,7 +53,8 @@ function getKey(action) {
 }
 
 function getKeyForOS(os, action) {
-  return KEYS[os][action];
+  const actions = KEYS[os] || KEYS.Linux;
```
Comment (darkwing) [inline src/components/SecondaryPanes/CommandBar.js]: This var name is throwing a lint warning: `no-shadow: 'actions' is already declared in the upper scope.`

We should use `OS` (caps) as the var name, IMO.
