### PR TITLE
Fix #7307 - Prevent enter key from submitting in outline

### LINKED ISSUE #7307: Crash when hitting Enter in Outline filter input
**Steps to reproduce**
1. Go to `data:text/html,<meta charset=utf8><script>function b(){}</script>`
1. Open the debugger
1. In the sources panel, select the only source available
1. Open the Outline panel
1. In the filter input, hit <kbd>Enter</kbd>

**Expected results**

if there's only 1 item in the list, (for this example, it is the case with `b`), we should jump to the function definition.

**Actual results**

⚠️ **The debugger panel goes blank** ⚠️

---

DevEdition is not affected, which is good. We should prioritize this in order to fix it before the 65 cycle.

### PR DESCRIPTION
**Pull request by darkwing**
Good catch by @nchevobbe

### CODE REVIEW

File: src/components/PrimaryPanes/OutlineFilter.js [hunk 1]
```diff
@@ -35,6 +35,8 @@ export default class OutlineFilter extends Component<Props, State> {
       // also bound to the ESC key
       e.preventDefault();
       this.props.updateFilter("");
+    } else if (e.key === "Enter") {
+      e.preventDefault();
```
Comment (nchevobbe) [inline src/components/PrimaryPanes/OutlineFilter.js]: could we add a comment explaining why it's needed ? With maybe a reference to the issue.
