### PR TITLE
Fixes Line Highlight Bug

### LINKED ISSUE #7757: [Editor] highlight line flashes when it is scrolled into view
STR:

1. click a breakpoint, which navigates to that location
2. scroll the editor so that that line is out of view
3. scroll it back into view

ER: nothing happens
AR: the line highlights again

The reason for this is that the HighlightLine component adds a class to the selected line and never removes it

Here's a start...
```diff
diff --git a/src/components/Editor/Editor.css b/src/components/Editor/Editor.css
index aed8d41c7..6f8e982f3 100644
--- a/src/components/Editor/Editor.css
+++ b/src/components/Editor/Editor.css
@@ -9,6 +9,7 @@
   --debug-line-error-border: rgb(255, 0, 0);
   --debug-expression-error-background: rgba(231, 116, 113, 0.3);
   --editor-header-height: 30px;
+  --highlight-line-duration: 1.5s;
 }
 
@@ -260,8 +263,9 @@ debug-expression-error {
 .new-debug-line-error .CodeMirror-activeline-background {
   display: none;
 }
+
 .highlight-line .CodeMirror-line {
-  animation: fade-highlight-out 1.5s normal forwards;
+  animation: fade-highlight-out var(--highlight-line-duration) normal forwards;
 }
 
 @keyframes fade-highlight-out {
diff --git a/src/components/Editor/HighlightLine.js b/src/components/Editor/HighlightLine.js
index 9c6530d13..f4107f4f0 100644
--- a/src/components/Editor/HighlightLine.js
+++ b/src/components/Editor/HighlightLine.js
@@ -121,7 +121,18 @@ export class HighlightLine extends Component<Props> {
     }
 
     const doc = getDocument(sourceId);
+    // adds the line here, but does not remove it
     doc.addLineClass(editorLine, "line", "highlight-line");
+    this.resetHighlightLine(doc, editorLine);
+  }
+
+  resetHighlightLine(doc, editorLine) {
+    const style = getComputedStyle(document.querySelector(".editor-wrapper"));
+    const duration = style.getPropertyValue("--highlight-line-duration");
+    setTimeout(
+      () => doc && doc.removeLineClass(editorLine, "line", "highlight-line"),
+      duration
+    );
   }

```

### PR DESCRIPTION
**Pull request by zerefwayne**
Fixes #7757 

### Summary of Change

* Fixed the issue of breakpoint line getting highlighted whenever it came into view.

### Test Plan

There wasn't any major change in the UI so I am planning to modify the tests later if required.

### Demo

7757-line-highlight

### CODE REVIEW

File: src/components/Editor/HighlightLine.js [hunk 1]
```diff
@@ -122,6 +122,21 @@ export class HighlightLine extends Component<Props> {
...
+    this.resetHighlightLine(doc, editorLine);
+  }
+
+  resetHighlightLine(doc, editorLine) {
+    const style = getComputedStyle(document.querySelector(".editor-wrapper"));
+    const durationString = style.getPropertyValue("--highlight-line-duration");
+    const duration =
+      parseFloat(durationString.substring(0, durationString.length - 1)) * 1000;
+
+    console.log(duration);
```
Comment (wldcordeiro) [inline src/components/Editor/HighlightLine.js]: Don't want to leave behind logs.

File: src/components/Editor/HighlightLine.js [hunk 2]
```diff
@@ -122,6 +122,21 @@ export class HighlightLine extends Component<Props> {
 
     const doc = getDocument(sourceId);
     doc.addLineClass(editorLine, "line", "highlight-line");
+    this.resetHighlightLine(doc, editorLine);
+  }
+
+  resetHighlightLine(doc, editorLine) {
```
Comment (wldcordeiro) [inline src/components/Editor/HighlightLine.js]: Looks like CI is failing and wants Flow types here.

```
yarn run v1.9.4
$ flow
Launching Flow server for /root/debugger.html
Spawned flow server (pid=3900)
Logs will go to /tmp/flow/zSrootzSdebugger.html.log
Monitor logs will go to /tmp/flow/zSrootzSdebugger.html.monitor_log
Error -------------------------------------------------------------------- src/components/Editor/HighlightLine.js:128:22

Missing type annotation for `doc`.

   128|   resetHighlightLine(doc, editorLine) {
                             ^^^


Error -------------------------------------------------------------------- src/components/Editor/HighlightLine.js:128:27

Missing type annotation for `editorLine`.

   128|   resetHighlightLine(doc, editorLine) {
                                  ^^^^^^^^^^


Error -------------------------------------------------------------------- src/components/Editor/HighlightLine.js:129:36

Cannot call `getComputedStyle` with `document.querySelector(...)` bound to `elt` because null [1] is incompatible with
`Element` [2].

   src/components/Editor/HighlightLine.js:129:36
    129|     const style = getComputedStyle(document.querySelector(".editor-wrapper"));
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

References:
   /tmp/flow/flowlib_23c0bb84/dom.js:952:50
    952|   querySelector(selector: string): HTMLElement | null;
                                                          ^^^^ [1]
   /tmp/flow/flowlib_23c0bb84/dom.js:3787:40
   3787| declare function getComputedStyle(elt: Element, pseudoElt?: string): any;
                                                ^^^^^^^ [2]



Found 3 errors
error Command failed with exit code 2.```

File: src/components/Editor/HighlightLine.js (hunk 1 above)
Comment (zerefwayne) [reply src/components/Editor/HighlightLine.js]: :+1:

File: src/components/Editor/HighlightLine.js (hunk 2 above)
Comment (zerefwayne) [reply src/components/Editor/HighlightLine.js]: @wldcordeiro Can you help me out with `Cannot call getComputedStyle with document.querySelector(...) bound to elt because null [1] is incompatible with
Element [2].`

**Comment by zerefwayne** [comment]
@wldcordeiro Passed both the checks. :+1:

File: src/components/Editor/Editor.css [hunk 3]
```diff
@@ -9,6 +9,7 @@
   --debug-line-error-border: rgb(255, 0, 0);
   --debug-expression-error-background: rgba(231, 116, 113, 0.3);
   --editor-header-height: 30px;
+  --highlight-line-duration: 1.5s;
```
Comment (wldcordeiro) [inline src/components/Editor/Editor.css]: I recently noticed an issue about deleting a CSS var that was used in only one place. Perhaps keeping this inline would be nice. 🤷‍♂️

File: src/components/Editor/HighlightLine.js [hunk 4]
```diff
@@ -122,6 +127,25 @@ export class HighlightLine extends Component<Props> {
...
+  }
+
+  resetHighlightLine(doc: SourceDocuments, editorLine: number) {
+    const line: HTMLElement | null = document.querySelector(".editor-wrapper");
+    if (line != null) {
+      const style = getComputedStyle(line);
+      const durationString = style.getPropertyValue(
+        "--highlight-line-duration"
+      );
+      const duration =
```
[the remark this answers is not in the document]
Comment (zerefwayne) [reply src/components/Editor/HighlightLine.js]: @wldcordeiro  But the stripped of "1500" would require a `parseInt(...)` right?

[the remark this answers is not in the document]
Comment (zerefwayne) [reply src/components/Editor/HighlightLine.js]: @wldcordeiro If it's not a big problem, are we good to go ahead with merging this? :100:

[the remark this answers is not in the document]
Comment (darkwing) [reply src/components/Editor/HighlightLine.js]: I really like that idea @wldcordeiro!  WIth that we can just do a string replacement of `ms`

[the remark this answers is not in the document]
Comment (zerefwayne) [reply src/components/Editor/HighlightLine.js]: @darkwing @wldcordeiro On it :+1:

**Comment by zerefwayne** [comment]
@darkwing @wldcordeiro Have a look at the changes. I've replaced it with 1500ms and stripped off the last two characters.
