### PR TITLE
Fix [QuickOpenModal] initial scroll

### LINKED ISSUE #5284: [QuickOpen] modal scrolls when displayed
Steps to reproduce:
1. In a page with a good number of files, open the debugger in the firefox devtools, docked at the bottom (not sure this is important but I could not reproduce with the launchpad)
2. Open the Source modal (Cmd + P)

Expected results:
I see the modal, scrolled at the top

Actual results:

The modal is displayed, but already scrolled

feb-01-2018 16-21-52

### PR DESCRIPTION
**Pull request by kootoopas**
Fixes #5284.

### Summary of Changes

* Apply delay if modal has just been enabled or if query didn't change. *(although `nowEnabled` is always `false` since `prevProps.enabled` is always `true` for some reason 🤔. maybe it's the because the `Modal` is wrapped with a `Transition`)*
* modify `scrollList` to accept optional delay flag

### Test Plan

- [x] Command-P opens the panel

### Screenshots/Videos (OPTIONAL)

quickopen-modal-initial-scroll-fix

### CODE REVIEW

**Comment by kootoopas** [comment]
Does circleci use prettier? The line that it throws for doesn't exceed 80.

File: src/components/QuickOpenModal.js [hunk 1]
```diff
@@ -96,12 +96,17 @@ export class QuickOpenModal extends Component<Props, State> {
   }
 
   componentDidUpdate(prevProps: Props) {
+    const nowEnabled = !prevProps.enabled && this.props.enabled;
+    const queryChanged = prevProps.query !== this.props.query;
```
Comment (lukaszsobek) [inline src/components/QuickOpenModal.js]: Not really needed to strict compare a value unless you expect it to be 0 or 1, this one is going to be a string.

File: src/components/shared/Modal.js [hunk 2]
```diff
@@ -20,6 +20,8 @@ type ModalProps = {
   handleClose: () => any
 };
 
+export const transitionTimeout = 175;
```
Comment (lukaszsobek) [inline src/components/shared/Modal.js]: Just curious, why should it be exactly 175?

Comment (kootoopas) [reply src/components/shared/Modal.js]: That was the value that the `timeout` prop of `<Transition/>` already had. I just made it exportable. I'm not sure why we have a delay for the transition of modals to be honest. :|

File: src/components/QuickOpenModal.js (hunk 1 above)
Comment (kootoopas) [reply src/components/QuickOpenModal.js]: It is a string. :) I dunno, I have the habit of always using strict comparisons since they're more precise. Are there any performance decrements?

**Comment by jasonLaster** [comment]
Hey @wldcordeiro mind taking a look. This touches your transition CSS logic which is kinda funky

File: src/components/shared/Modal.js (hunk 2 above)
Comment (wldcordeiro) [reply src/components/shared/Modal.js]: https://reactcommunity.org/react-transition-group/#Transition-prop-timeout

> The duration of the transition, in milliseconds. Required unless addEventListener is provided.

File: src/components/QuickOpenModal.js (hunk 1 above)
Comment (AnshulMalik) [reply src/components/QuickOpenModal.js]: Strict comparison should be faster

Comment (wldcordeiro) [reply src/components/QuickOpenModal.js]: Personally I prefer the strict checks for all things except for when you're comparing to `null`/`undefined` where `if (foo == null)` is equivalent to `if (foo === null || foo === undefined)` but yeah. If I had a thing I'd prefer here it'd be this but only because I like explicitly plucking the props/prevProps I care about.

```js
componentDidUpdate({ enabled: prevEnabled, query: prevQuery }) {
  const { enabled, query } = this.props;
  const nowEnabled = !prevEnabled && enabled;
  const queryChanged = prevQuery !== query;
  // ...
}

File: src/utils/result-list.js [hunk 3]
```diff
@@ -3,19 +3,32 @@
  * file, You can obtain one at <http://mozilla.org/MPL/2.0/>. */
 
 import { isFirefox } from "devtools-config";
+import {
```
Comment (wldcordeiro) [inline src/utils/result-list.js]: Weird that CI is tripping here. Maybe just leave the original name?

File: src/components/shared/Modal.js (hunk 2 above)
Comment (kootoopas) [reply src/components/shared/Modal.js]: Huh, weird. I thought that the timeout was just a delay and when it ends, the transition is fired. I gave it a value of 2000ms just to check what it does and the transition speed of the modal appearance is the same. So maybe it is a delay. Am I missing something? 🤔 

I think that we can make it faster and give the modal appearance a more responsive feel if we make the timeout 25ms.

File: src/utils/result-list.js (hunk 3 above)
Comment (kootoopas) [reply src/utils/result-list.js]: done did it :)
