### PR TITLE
Chrome debug fix

### LINKED ISSUE #7560: Chrome support
After back support for the chrome client, as next steps we need to fix a couple of things.

- [x] show debug line
- [ ] support preview
- [ ] show scopes (reps is out of scope (pun not intended))
- [ ] support watch expressions

### PR DESCRIPTION
**Pull request by bomsy**
Fixes #7560

### Summary of Changes

* add `thread`
* Fixes the debug line
* Enables basic pause functionality (Shows callstack and pause buttons)

To come
* Scopes panel
* Preview

#### Before
image

#### After

image

### CODE REVIEW

File: src/client/chrome/events.js [hunk 1]
```diff
@@ -74,8 +76,7 @@ async function paused({
   if (clientType == "chrome") {
     pageAgent.configureOverlay({ message: "Paused in debugger.html" });
   }
-
-  await actions.paused({ frame, why, frames, loadedObjects });
+  await actions.paused({ thread: "root", frame, why, frames, loadedObjects });
```
Comment (bomsy) [inline src/client/chrome/events.js]: @jasonLaster not sure if this the best thread value, couldn't find something better, your thoughts?

Comment (jasonLaster) [reply src/client/chrome/events.js]: haha - it's fine...
