### PR TITLE
Use renderStacktrace prop if provided to render Error rep stacktrace

### LINKED ISSUE #7130: Use the `renderStacktrace` prop to render the stacktrace in Error reps
In [Bug 1390768](https://bugzilla.mozilla.org/show_bug.cgi?id=1390768), we want to use debugger's `Frames` component to render stacktraces in the console.
We also want to be able to use the same component that we will create there for Errors as well.
This means that in the `Error` rep, if a `renderStacktrace` prop is passed, it should be used to render the stacktrace.
if it is not passed, then we should default to the current rendering.

### PR DESCRIPTION
**Pull request by nchevobbe**
This will allow us to use the same component
in the console and in reps for example.
If the prop is not passed, it defers to the
current stacktrace rendering.

Fixes #7130

### CODE REVIEW

**Comment by nchevobbe** [comment]
> I don't think we want the change to `assets/module-manifest.json`

good catch!

**Comment by darkwing** [comment]
@janodvarko Just a heads up you were requested for review here

File: packages/devtools-reps/src/reps/error.js [hunk 1]
```diff
@@ -20,7 +20,8 @@ const IGNORED_SOURCE_URLS = ["debugger eval code"];
 ErrorRep.propTypes = {
   object: PropTypes.object.isRequired,
   // @TODO Change this to Object.values when supported in Node's version of V8
-  mode: PropTypes.oneOf(Object.keys(MODE).map(key => MODE[key]))
+  mode: PropTypes.oneOf(Object.keys(MODE).map(key => MODE[key])),
+  renderStacktrace: PropTypes.func
```
Comment (janodvarko) [inline packages/devtools-reps/src/reps/error.js]: It would be great to have an explanatory comment for the new prop

```// Custom function used to render the stack trace (optional)
  renderStacktrace: PropTypes.func
```

Comment (nchevobbe) [reply packages/devtools-reps/src/reps/error.js]: done ✅
