### PR TITLE
[Breakpoints] Persist XHR breakpoints on refresh

### LINKED ISSUE #7192: [XHR Breakpoints] "Pause on any URL" Not Persisting Upon Refresh in Panel
When we check the "Pause on any URL" checkbox in the XHR breakpoint panel, the checkbox unchecks itself upon a refresh or navigation.  We need this setting to persist just as Pause on Exceptions does.

### PR DESCRIPTION
**Pull request by jainsneha23**
Fixes #7192 

### Summary of Changes
* Persist XHR breakpoints on navigation

### Test Plan

- [x] Open debugger and open TodoMVC in browser
- [x] Check Pause on any URL
- [x] Add some XHR breakpoints
- [x] Refresh the debugger, and see the XHR breakpoints, and checkbox state doesn't change
- [x] Refresh the browser with todo mvc, and see the XHR breakpoints, and checkbox state doesn't change

http://g.recordit.co/MD2yA91HM3.gif

### CODE REVIEW

File: src/reducers/breakpoints.js [hunk 1]
```diff
@@ -77,7 +77,7 @@ function update(
     }
 
     case "NAVIGATE": {
-      return initialBreakpointsState();
+      return initialBreakpointsState(state.xhrBreakpoints);
```
Comment (jasonLaster) [inline src/reducers/breakpoints.js]: maybe we just don't want to handle the NAVIGATE case?

**Comment by darkwing** [comment]
Excellent!  I love it!  Thank you @jainsneha23 !
