### PR TITLE
Fix #1510. [Editor] Multiple Highlight Lines

### LINKED ISSUE #1510: [Editor] Multiple Highlight Lines
It's possible to add breakpoints in different sources, such that clicking on 

Steps to Reproduce:
* 1. go to todomvc
* 2. add breakpoints in app-view and todo-view
* 3. click on the breakpoints in the list alternating between todo-view and app-view breakpoints

#### Patch

```diff
diff --git a/src/test/mochitest/browser_dbg-editor-highlight.js b/src/test/mochitest/browser_dbg-editor-highlight.js
index d7892e6..7a9e2a1 100644
--- a/src/test/mochitest/browser_dbg-editor-highlight.js
+++ b/src/test/mochitest/browser_dbg-editor-highlight.js
@@ -5,10 +5,12 @@
 // matter if the source text doesn't exist yet or even if the source
 // doesn't exist.

+// we do have some tests for highlighting
+
 add_task(function* () {
   const dbg = yield initDebugger("doc-scripts.html");
   const { selectors: { getSourceText }, getState } = dbg;
-  const sourceUrl = EXAMPLE_URL + "long.js";
+  const sourceUrl = `${EXAMPLE_URL }long.js`;

   // The source itself doesn't even exist yet, and using
   // `selectSourceURL` will set a pending request to load this source
diff --git a/src/test/mochitest/browser_dbg-editor-select.js b/src/test/mochitest/browser_dbg-editor-select.js
index 8b954f8..e490c1e 100644
--- a/src/test/mochitest/browser_dbg-editor-select.js
+++ b/src/test/mochitest/browser_dbg-editor-select.js
@@ -4,6 +4,8 @@
 // Tests that the editor highlights the correct location when the
 // debugger pauses

+// and some tests for debug-line too
+
 // checks to see if the first breakpoint is visible
 function isElementVisible(dbg, elementName) {
   const bpLine = findElement(dbg, elementName);
```

We also have some tests

```diff
diff --git a/src/test/mochitest/browser_dbg-editor-highlight.js b/src/test/mochitest/browser_dbg-editor-highlight.js
index d7892e6..7a9e2a1 100644
--- a/src/test/mochitest/browser_dbg-editor-highlight.js
+++ b/src/test/mochitest/browser_dbg-editor-highlight.js
@@ -5,10 +5,12 @@
 // matter if the source text doesn't exist yet or even if the source
 // doesn't exist.

+// we do have some tests for highlighting
+
 add_task(function* () {
   const dbg = yield initDebugger("doc-scripts.html");
   const { selectors: { getSourceText }, getState } = dbg;
-  const sourceUrl = EXAMPLE_URL + "long.js";
+  const sourceUrl = `${EXAMPLE_URL }long.js`;

   // The source itself doesn't even exist yet, and using
   // `selectSourceURL` will set a pending request to load this source
diff --git a/src/test/mochitest/browser_dbg-editor-select.js b/src/test/mochitest/browser_dbg-editor-select.js
index 8b954f8..e490c1e 100644
--- a/src/test/mochitest/browser_dbg-editor-select.js
+++ b/src/test/mochitest/browser_dbg-editor-select.js
@@ -4,6 +4,8 @@
 // Tests that the editor highlights the correct location when the
 // debugger pauses

+// and some tests for debug-line too
+
 // checks to see if the first breakpoint is visible
 function isElementVisible(dbg, elementName) {
   const bpLine = findElement(dbg, elementName);
```

### PR DESCRIPTION
**Pull request by Dalimil**
Associated Issue: #1510 

We would need to keep lastJumpLine for every tab separately (not just one globally) - so the easiest thing to do to fix this is to go through all bp lines instead.

### CODE REVIEW

File: src/components/Editor.js [hunk 1]
```diff
@@ -292,9 +292,11 @@ const Editor = React.createClass({
...
     // class, etc).
     if (this.lastJumpLine) {
-      codeMirror.removeLineClass(
-        this.lastJumpLine - 1, "line", "highlight-line"
-      );
+      this.props.breakpoints.map(bp => {
+        codeMirror.removeLineClass(
+          bp.location.line - 1, "line", "highlight-line"
+        );
+      });
```
Comment (jasonLaster) [inline src/components/Editor.js]: hmm, we can navigate to any line by clicking on console link, or other features like "jump to original location"... so breakpoints is not enough

what if we just iterated over all of the code mirror lines and removed this class?

**Comment by jasonLaster** [comment]
@Dalimil I cleaned up the codemirror iteration code a bit. Let me know what you think
