### PR TITLE
Fix a couple bugs with windowless worker debugging.

### LINKED ISSUE #7710: [tracking] Worker Debugging
Server-side meta bug: [1520698](https://bugzilla.mozilla.org/show_bug.cgi?id=1520698).

#### Todos
- [x] refreshing clears selected source #7708 
- [ ] [Workers] Use one tree instead of one tree per thread #8005 
- [x] remove sources when a worker is removed #7660

### PR DESCRIPTION
**Pull request by bhackett1024**
Addresses #7710 part 2

### Summary of Changes

* Fixes bug where refreshing a page that pauses at startup and has workers ends up in a messed up state where pause information is shown incorrectly.  The problem is that updating the redux state after a thread resumes updated the state of the current thread, instead of the thread that actually resumed.

* Fixes bug where loading devtools where persistent state referred to a worker source could access an undefined source object and throw an exception that prevents the debugger from loading.

### Test Plan

Manually verified issues were fixed.  These are hard to write tests for unfortunately :/

### CODE REVIEW

File: src/actions/tabs.js [hunk 1]
```diff
@@ -106,6 +106,7 @@ export function closeTabsForMissingThreads(workers: Worker[]) {
       if (sourceId) {
         const source = getSourceFromId(getState(), sourceId);
         if (
+          source &&
```
Comment (jasonLaster) [inline src/actions/tabs.js]: I think we should use getSource instead of getSourceFromId. This way we're telling flow source can be null.

File: src/actions/pause/resumed.js [hunk 2]
```diff
@@ -4,26 +4,26 @@
...
-export function resumed() {
+export function resumed(packet: ResumedPacket) {
   return async ({ dispatch, client, getState }: ThunkArgs) => {
     const why = getPauseReason(getState());
     const wasPausedInEval = inDebuggerEval(why);
     const wasStepping = isStepping(getState());
-    const thread = getCurrentThread(getState());
 
-    dispatch({ type: "RESUME", thread });
+    dispatch({ type: "RESUME", thread: packet.from });
```
Comment (jasonLaster) [inline src/actions/pause/resumed.js]: Nice catch.

File: src/actions/tabs.js (hunk 1 above)
Comment (bhackett1024) [reply src/actions/tabs.js]: Sure, just pushed a fix for this.  Having these two methods with identical implementations and different return types is kind of silly though, I'll try to fix this as part of bug 1518884.

Comment (jasonLaster) [reply src/actions/tabs.js]: agreed... `getSourceFromId` was a bad idea :/
