### PR TITLE
Fix 7830 mapBindings throws 

### LINKED ISSUE #7830: mapBindings throws when expression has declarations without initial values
Given the following diff: 

```diff
diff --git a/src/workers/parser/tests/mapBindings.spec.js b/src/workers/parser/tests/mapBindings.spec.js
index f063e73c4..826fcdcfe 100644
--- a/src/workers/parser/tests/mapBindings.spec.js
+++ b/src/workers/parser/tests/mapBindings.spec.js
@@ -44,6 +44,16 @@ describe("mapExpressionBindings", () => {
       expression: "const a = 2, b = 3",
       newExpression: "self.a = 2; self.b = 3"
     },
+    {
+      name: "declaration with separate assignment",
+      expression: "let a; a = 2;",
+      newExpression: "self.a = undefined; self.a = 2;"
+    },
+    {
+      name: "multiple declarations with no assignment",
+      expression: "let a = 2, b;",
+      newExpression: "self.a = 2; self.b = undefined;"
+    },
     {
       name: "local bindings become assignments",
       bindings: ["a"],
```

`src/workers/parser/tests/mapBindings.spec.js` fails with the following error message: 

```
TypeError: Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got null

      57 |   return node.declarations.map(declaration =>
      58 |     t.expressionStatement(
    > 59 |       t.assignmentExpression(
         |         ^
      60 |         "=",
      61 |         getAssignmentTarget(declaration.id, bindings),
      62 |         declaration.init

      at Object.validate (node_modules/@babel/types/lib/definitions/utils.js:128:13)
      at validate (node_modules/@babel/types/lib/validators/validate.js:17:9)
      at builder (node_modules/@babel/types/lib/builders/builder.js:46:27)
      at Object.AssignmentExpression (node_modules/@babel/types/lib/builders/generated/index.js:233:31)
      at node.declarations.map.declaration (src/workers/parser/mapBindings.js:59:9)
          at Array.map (<anonymous>)
      at globalizeDeclaration (src/workers/parser/mapBindings.js:57:28)
      at t.traverse (src/workers/parser/mapBindings.js:127:24)
      at traverseSimpleImpl (node_modules/@babel/types/lib/traverse/traverse.js:27:14)
      at traverseSimpleImpl (node_modules/@babel/types/lib/traverse/traverse.js:41:9)
      at traverseSimpleImpl (node_modules/@babel/types/lib/traverse/traverse.js:49:7)
      at Object.traverse (node_modules/@babel/types/lib/traverse/traverse.js:21:3)
      at mapExpressionBindings (src/workers/parser/mapBindings.js:100:5)
      at includedTest (src/workers/parser/tests/mapBindings.spec.js:27:26)
      at Object.cb (node_modules/jest-in-case/index.js:40:20)
```

---

This is because we always create an `assignmentExpression` when we encounter a variable declaration, even if the original declaration does not have an initial assignment.

### PR DESCRIPTION
**Pull request by P0lip**
Fixes #7830  

### Summary of Changes

* Added support for declarations with no initial values

### Test Plan

Well, I rely on tests

Here's the Debugger's Testing doc
https://docs.google.com/document/d/1oBMRxV8A2ag2t22YsQOxTdEv0mXKzIg0tggJjRkU1S0/edit#.
Feel free to improve it!

### CODE REVIEW

File: src/workers/parser/mapBindings.js [hunk 1]
```diff
@@ -60,7 +60,7 @@ function globalizeDeclaration(node, bindings) {
       t.assignmentExpression(
         "=",
         getAssignmentTarget(declaration.id, bindings),
-        declaration.init
+        declaration.init || t.identifier("undefined")
```
Comment (loganfsmyth) [inline src/workers/parser/mapBindings.js]: Would you be up for using `void 0` here so we don't risk picking up local declarations of variables named `undefined`, e.g. `var undefined = 4;` is fine, so could break this.

```
t.unaryExpression("void", t.numericLiteral(0))
```
