### PR TITLE
Fix scopes with selected frame

### LINKED ISSUE #579: Scopes pane doesnt update
When selecting different frames the scopes pane does not update with the proper variables. I was able to fix this by changing the pause reducer action type SECLECT_FRAME

```
    case constants.SELECT_FRAME:
      let intermState = state.setIn(["pause", "frame", "scope"], fromJS(action.frame.scope));
      return intermState.set("selectedFrame", action.frame);
```

Not sure this is the best way to handle this though.

### PR DESCRIPTION
**Pull request by jasonLaster**
Fixes #579 

@JasonWeathersby the change ended up being larger than I expected and certainly larger than your one line change! The big difference is that here the scopes pane uses the selectedFrame as a data source as opposed to updating the pause info directly.

### CODE REVIEW

File: public/js/components/Scopes.js [hunk 1]
```diff
@@ -3,30 +3,38 @@ const { bindActionCreators } = require("redux");
...
+  return args.concat(variables)
+  .filter(binding => !excludeVariable(binding))
     .map(binding => ({
       name: binding[0],
       path: parentName + "/" + binding[0],
-      contents: binding[1].toJS()
-    }))
-    .toArray();
+      contents: binding[1]
+    }));
```
Comment (jasonLaster) [inline public/js/components/Scopes.js]: immutable's api is certainly more verbose

File: public/js/components/Scopes.js [hunk 2]
```diff
@@ -3,30 +3,38 @@ const { bindActionCreators } = require("redux");
...
+
 // Create the tree nodes representing all the variables and arguments
 // for the bindings from a scope.
 function getBindingVariables(bindings, parentName) {
-  return bindings
-    .get("arguments").map(arg => arg.entrySeq().get(0))
-    .concat(bindings.get("variables").entrySeq())
-    .filter(binding => (!binding[1].hasIn(["value", "missingArguments"]) &&
-                        !binding[1].hasIn(["value", "optimizedOut"])))
+  const args = [].concat(...bindings.arguments.map(toPairs));
```
Comment (jasonLaster) [inline public/js/components/Scopes.js]: I plan on switching this to just a flatten call (probably lodash)

File: public/js/components/Scopes.js [hunk 3]
```diff
@@ -96,18 +104,18 @@ function getScopes(pauseInfo) {
         vars = vars.concat(getSpecialVariables(pauseInfo, title));
       }
 
-      if (vars.length) {
+      if (vars && vars.length) {
```
Comment (jasonLaster) [inline public/js/components/Scopes.js]: i'll drop this check and make sure vars is always an array

File: public/js/components/Scopes.js [hunk 4]
```diff
@@ -116,18 +124,26 @@ const Scopes = React.createClass({
...
+    loadObjectProperties: PropTypes.func,
+    selectedFrame: PropTypes.map
   },
 
   displayName: "Scopes",
 
   getInitialState() {
-    return { scopes: getScopes(this.props.pauseInfo) };
+    const { pauseInfo, selectedFrame } = this.props;
+    return { scopes: getScopes(pauseInfo, selectedFrame) };
```
Comment (jasonLaster) [inline public/js/components/Scopes.js]: what was the reason we used state here? could we have changed Scopes to use `componentShouldUpdate`

**Comment by JasonWeathersby** [comment]
Jason this is more verbose but more correct :) . My initial go was similar in that I added the selectedFrame to the scopes component and modified the getScopes function.

**Comment by jasonLaster** [comment]
Neat. Thanks for finding it again.

What were you doing with the debugger at the time?

**Comment by JasonWeathersby** [comment]
I was documenting the pause reducer and I noticed that the scopes variables where coming from pause state instead of selected frame.

**Comment by jasonLaster** [comment]
haha - love it.

**Comment by jasonLaster** [comment]
Interesting finding by the way, I did most of the development for this feature with this cypress test. 

```js
  it.only("(Firefox) Test Scopes", function() {
    debugPage("todomvc");
    goToSource("todo-view");
    toggleBreakpoint(33);

    // pause and check the first frame
    addTodo();
    stepIn();
  });
```

Having it meant that I could make a change and then quickly be back in the right place to debug it. Honestly, I probably could do the same thing with storybook and a fixture. I'm not sure if HMR would work with the way scope state is stored, but that could be another technique

File: public/js/components/Scopes.js (hunk 2 above)
Comment (jlongster) [inline public/js/components/Scopes.js]: Shouldn't need that; the way the data is shaped you can just do `.map(x => toPairs(x)[0]` like before. It's stupid, but it's because the object only ever going to have one key and one value.

File: public/js/components/Scopes.js (hunk 1 above)
Comment (jlongster) [inline public/js/components/Scopes.js]: I'd rather keep the logic of `excludeVariable` in here, it feels like over-abstracting. How come you check of `binding[1]` is truthy in the function?  You should just able tp filter out `binding[1].value.missingArguments || binding[1].value.optimizedOut;` which is pretty short.

**Comment by jlongster** [comment]
This is great, I like that the scopes is a normal JS object as it is a bit easier to dig around in. I want to avoid converting the pause object into an immutable obj at some point too. Thanks for fixing this!

**Comment by jasonLaster** [comment]
Just fixed a related issue where some scopes had the same sibling key because they shared the same function display name or more likely were "(anonymous)".

**Comment by jlongster** [comment]
I don't think `Scopes` is hot-reloadable as it stands because it's a connected component. Definitely should look into how to enable it for more components.

File: public/js/components/Scopes.js (hunk 4 above)
Comment (jlongster) [inline public/js/components/Scopes.js]: It's stateful because we shouldn't keep transient objects like a tree structure in the redux state. It just is dynamically generated from the state.

**Comment by jlongster** [comment]
Did you accidentally merge this? Not sure you saw my review :)

**Comment by jasonLaster** [comment]
Nope. Missed it. Will fix that now. Thanks for checking!

File: public/js/components/Scopes.js (hunk 1 above)
Comment (jasonLaster) [inline public/js/components/Scopes.js]: that's a good point
