### PR TITLE
[Exceptions] Update Checkbox Options Language

### LINKED ISSUE #6064: [Breakpoints] (Nit) Change Exception Checkbox Labels
Needs to change to:

- [ ] Pause on Exceptions
  - [ ] Pause on Caught Exceptions

### PR DESCRIPTION
**Pull request by darkwing**
Fixes Issue: https://github.com/devtools-html/debugger.html/issues/6064

pausing

## ToDo
- [x] Upon refresh of the debugger I see the following error: "Error: non-bool passed to setBoolPref (Services.js:79:12)"; this error bricks the entire debugger.  For some reason `pause-on-caught-exceptions` is being set to `undefined`.  Tracing the `prefs` object and `dbg.store.getState().pause.shouldPauseOnCaughtExceptions` shows the values are being changed properly, so no idea where this error is coming from.

- [ ] I'm trying this out in the "Exceptions" example in the `debugger-examples` repo (http://localhost:7999/exceptions.html) and ... it's not working -- the caught exceptions are being stopped at regardless of this checkbox setting.  *Actually, with all checkboxes off in current master, the behavior is the same*

### CODE REVIEW

File: assets/panel/debugger.properties [hunk 1]
```diff
@@ -104,6 +104,10 @@ pauseOnExceptionsItem=Pause on exceptions
 # when the debugger will not pause on any caught exception
 ignoreCaughtExceptionsItem=Ignore caught exceptions
 
+# LOCALIZATION NOTE (pauseOnCaughtExceptionsItem): The pause on exceptions checkbox description
+# when the debugger should puase on caught exceptions
```
Comment (flodolo) [inline assets/panel/debugger.properties]: typo: puase

File: src/client/firefox/commands.js [hunk 2]
```diff
@@ -272,11 +272,13 @@ async function getFrameScopes(frame: Frame): Promise<*> {
...
   shouldPauseOnExceptions: boolean,
-  shouldIgnoreCaughtExceptions: boolean
+  shouldPauseOnCaughtExceptions: boolean
 ): Promise<*> {
   return threadClient.pauseOnExceptions(
     shouldPauseOnExceptions,
-    shouldIgnoreCaughtExceptions
+    // Providing opposite value because server
+    // uses "shouldIgnoreCaughtExceptions"
+    !shouldPauseOnCaughtExceptions
```
Comment (darkwing) [inline src/client/firefox/commands.js]: The way I'm thinking about this, we can change everything on our side, but simply reverse the value we're using when sending to server since the server still works on ignoreCaughtExceptions.

File: src/actions/pause/pauseOnExceptions.js [hunk 3]
```diff
@@ -14,16 +14,16 @@ import type { ThunkArgs } from "../types";
...
   return ({ dispatch, client }: ThunkArgs) => {
     dispatch({
       type: "PAUSE_ON_EXCEPTIONS",
       shouldPauseOnExceptions,
-      shouldIgnoreCaughtExceptions,
+      shouldPauseOnCaughtExceptions,
       [PROMISE]: client.pauseOnExceptions(
         shouldPauseOnExceptions,
-        shouldIgnoreCaughtExceptions
+        !shouldPauseOnCaughtExceptions
```
Comment (darkwing) [inline src/actions/pause/pauseOnExceptions.js]: I *think* we need the `!` here.

File: assets/panel/debugger.properties (hunk 1 above)
Comment (darkwing) [reply assets/panel/debugger.properties]: WHY DO I KEEP DOING THAT?!  Seriously, I did that like 100 times while working on this stuff.  Making me so mad.

**Comment by jasonLaster** [comment]
Looks great! I'll test soon

**Comment by jasonLaster** [comment]
code looks good, but i'm seeing this error when i refresh




Also, when i use this page to test
http://firefox-dev.tools/debugger-examples/examples/exceptions.html

it looks like i'm always pausing on caught exceptions, even w/o the checkbox checked

**Comment by darkwing** [comment]
Updates made, tests passing, worth another look @jasonLaster
